"""initial_schema

Revision ID: f54e016350b3
Revises: 
Create Date: 2026-07-10 11:32:31.235019
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f54e016350b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor'), 'audit_events', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('included_items', sa.JSON(), nullable=False),
    sa.Column('excluded_items', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workflow_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_code'), 'categories', ['code'], unique=True)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_status'), 'categories', ['status'], unique=False)
    op.create_index(op.f('ix_categories_workflow_status'), 'categories', ['workflow_status'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('requested_directories', sa.JSON(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('inserted_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('encyclopedia_sections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('section_key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('generation_mode', sa.String(length=32), nullable=False),
    sa.Column('locked_by_human', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('updated_by', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'section_key', name='uq_category_section')
    )
    op.create_index(op.f('ix_encyclopedia_sections_category_id'), 'encyclopedia_sections', ['category_id'], unique=False)
    op.create_table('encyclopedia_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('content_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'version_number', name='uq_category_version')
    )
    op.create_index(op.f('ix_encyclopedia_versions_category_id'), 'encyclopedia_versions', ['category_id'], unique=False)
    op.create_index(op.f('ix_encyclopedia_versions_status'), 'encyclopedia_versions', ['status'], unique=False)
    op.create_table('listing_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('marketplace', sa.String(length=16), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=False),
    sa.Column('rating_value', sa.Float(), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('bsr_rank', sa.Integer(), nullable=True),
    sa.Column('bsr_category', sa.String(length=255), nullable=True),
    sa.Column('bullet_points', sa.JSON(), nullable=False),
    sa.Column('product_info', sa.JSON(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('images', sa.JSON(), nullable=False),
    sa.Column('videos', sa.JSON(), nullable=False),
    sa.Column('customers_say', sa.JSON(), nullable=False),
    sa.Column('qa_content', sa.JSON(), nullable=False),
    sa.Column('aplus_content', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marketplace', 'asin', 'scraped_at', name='uq_listing_snapshot')
    )
    op.create_index('ix_listing_category_brand', 'listing_snapshots', ['category_id', 'brand'], unique=False)
    op.create_index(op.f('ix_listing_snapshots_asin'), 'listing_snapshots', ['asin'], unique=False)
    op.create_index(op.f('ix_listing_snapshots_brand'), 'listing_snapshots', ['brand'], unique=False)
    op.create_index(op.f('ix_listing_snapshots_category_id'), 'listing_snapshots', ['category_id'], unique=False)
    op.create_index(op.f('ix_listing_snapshots_content_hash'), 'listing_snapshots', ['content_hash'], unique=False)
    op.create_index(op.f('ix_listing_snapshots_marketplace'), 'listing_snapshots', ['marketplace'], unique=False)
    op.create_index(op.f('ix_listing_snapshots_scraped_at'), 'listing_snapshots', ['scraped_at'], unique=False)
    op.create_table('source_materials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_materials_category_id'), 'source_materials', ['category_id'], unique=False)
    op.create_index(op.f('ix_source_materials_source_type'), 'source_materials', ['source_type'], unique=False)
    op.create_table('evidence_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('section_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('source_id', sa.BigInteger(), nullable=False),
    sa.Column('locator', sa.String(length=500), nullable=True),
    sa.Column('support_type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['encyclopedia_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_links_section_id'), 'evidence_links', ['section_id'], unique=False)
    op.create_table('publication_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_doc_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=120), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('preview_content', sa.Text(), nullable=False),
    sa.Column('published_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['encyclopedia_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'version_id', name='uq_provider_version')
    )
    op.create_index(op.f('ix_publication_records_category_id'), 'publication_records', ['category_id'], unique=False)
    op.create_index(op.f('ix_publication_records_status'), 'publication_records', ['status'], unique=False)
    op.create_index(op.f('ix_publication_records_version_id'), 'publication_records', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_records_version_id'), table_name='publication_records')
    op.drop_index(op.f('ix_publication_records_status'), table_name='publication_records')
    op.drop_index(op.f('ix_publication_records_category_id'), table_name='publication_records')
    op.drop_table('publication_records')
    op.drop_index(op.f('ix_evidence_links_section_id'), table_name='evidence_links')
    op.drop_table('evidence_links')
    op.drop_index(op.f('ix_source_materials_source_type'), table_name='source_materials')
    op.drop_index(op.f('ix_source_materials_category_id'), table_name='source_materials')
    op.drop_table('source_materials')
    op.drop_index(op.f('ix_listing_snapshots_scraped_at'), table_name='listing_snapshots')
    op.drop_index(op.f('ix_listing_snapshots_marketplace'), table_name='listing_snapshots')
    op.drop_index(op.f('ix_listing_snapshots_content_hash'), table_name='listing_snapshots')
    op.drop_index(op.f('ix_listing_snapshots_category_id'), table_name='listing_snapshots')
    op.drop_index(op.f('ix_listing_snapshots_brand'), table_name='listing_snapshots')
    op.drop_index(op.f('ix_listing_snapshots_asin'), table_name='listing_snapshots')
    op.drop_index('ix_listing_category_brand', table_name='listing_snapshots')
    op.drop_table('listing_snapshots')
    op.drop_index(op.f('ix_encyclopedia_versions_status'), table_name='encyclopedia_versions')
    op.drop_index(op.f('ix_encyclopedia_versions_category_id'), table_name='encyclopedia_versions')
    op.drop_table('encyclopedia_versions')
    op.drop_index(op.f('ix_encyclopedia_sections_category_id'), table_name='encyclopedia_sections')
    op.drop_table('encyclopedia_sections')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_categories_workflow_status'), table_name='categories')
    op.drop_index(op.f('ix_categories_status'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_code'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###

